# Generated by Django 3.0.3 on 2021-06-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=500)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Duration of test in minutes')),
                ('passing_score', models.IntegerField(help_text='Required score in %')),
            ],
        ),
    ]
