# Generated by Django 3.0.3 on 2021-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0002_auto_20210610_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='passing_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.IntegerField(),
        ),
    ]
